### ISSUE TITLE
Update releases

### ISSUE THREAD

**Issue by jdpleiness** [cloudposse/terraform-aws-cloudtrail-cloudwatch-alarms#15]
Please create new releases for each stable code change so this great module can be used safely in production by others.

**Comment by aknysh** [comment]
@jdpleiness  thanks, that's what we do.
the latest release https://github.com/cloudposse/terraform-aws-cloudtrail-cloudwatch-alarms/releases/tag/0.3.0

let us know if you find when the code was merged to master but a release was not created - we'll fix that
