### ISSUE TITLE
Support Terraform 0.14

### ISSUE THREAD

**Issue by tquach** [cloudposse/terraform-aws-cloudtrail-cloudwatch-alarms#24]
# Describe the Feature
Support for Terraform version 0.14. 

# Expected Behavior
I expect to not get "this module is not compatible, either change the source or contact..." messages when I run `terraform plan`.

# Use Case
Upgrading to terraform 0.14 prevents us from using this module. 

This module depends on https://github.com/cloudposse/terraform-null-label?ref=v0.19.2 which in turn has a ceiling on Terraform version 0.14. 

The terraform-null-label module has since [released version 0.20.0](https://github.com/cloudposse/terraform-null-label/releases/tag/0.20.0) which removes the version ceiling. 

# Alternatives Considered
Use a fork that has support for 0.14.0

**Comment by osterman** [comment]
This has been upgraded to HCL2

**Comment by Warns** [comment]
Hi @osterman @tquach from your comments I couldn't quite get what workaround you have done for this, I'm getting the `null` value error when running with terraform version `0.15.0` 

```
│ Error: Null value found in list
│
│   on modules/aws-cloudtrail-cloudwatch-alarms/main.tf line 121, in data "aws_iam_policy_document" "sns_topic_policy":
│  121:     resources = [local.sns_topic_arn]
│
│ Null values are not allowed for this attribute value.
```
